apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-0
  labels:
    for: kafka-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/kafka/data-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-1
  labels:
    for: kafka-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/kafka/data-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-2
  labels:
    for: kafka-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/kafka/data-2