apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    service: kafka
spec:
  clusterIP: None
  selector:
    service: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: controller
      port: 19092
      targetPort: 19092
    - name: broker
      port: 19093
      targetPort: 19093
