apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:contrib-v1.29.1
          ports:
            - containerPort: 10000
              name: broker-0
            - containerPort: 10001
              name: broker-1
            - containerPort: 10002
              name: broker-2
          command:
            - "/usr/local/bin/envoy"
            - "--config-path"
            - "/etc/envoy/envoy.yaml"
            - "-l"
            - "debug"
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
