apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  selector:
    app: envoy
  type: NodePort
  ports:
    - name: broker-0
      port: 10000
      targetPort: 10000
      nodePort: 30000

    - name: broker-1
      port: 10001
      targetPort: 10001
      nodePort: 30001

    - name: broker-2
      port: 10002
      targetPort: 10002
      nodePort: 30002
      